/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'sectionViews' : Array<[string, bigint]>,
  'pageVisits' : Array<[string, bigint]>,
  'dailyVisitors' : Array<[string, bigint]>,
  'elementClicks' : Array<[string, bigint]>,
}
export interface Appointment {
  'id' : string,
  'customerName' : string,
  'timeSlotId' : string,
  'bookedBy' : Principal,
}
export interface BlogPost {
  'id' : string,
  'embeddedImages' : Array<EmbeddedImage>,
  'title' : string,
  'content' : string,
  'associatedFiles' : Array<ExternalBlob>,
  'editHistory' : Array<EditRecord>,
  'publicationDate' : Time,
  'excerpt' : string,
}
export interface EditRecord {
  'previousTitle' : string,
  'editor' : Principal,
  'previousExcerpt' : string,
  'timestamp' : Time,
  'previousContent' : string,
}
export interface EmbeddedImage {
  'id' : string,
  'url' : ExternalBlob,
  'size' : string,
  'position' : bigint,
  'altText' : string,
}
export type ExternalBlob = Uint8Array;
export interface HomepageSection {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'sectionType' : SectionType,
  'description' : string,
  'visible' : boolean,
}
export interface LinkItem {
  'id' : string,
  'url' : string,
  'textLabel' : string,
  'order' : bigint,
  'visible' : boolean,
}
export interface Livestream {
  'id' : string,
  'startTime' : Time,
  'title' : string,
  'externalLink' : string,
  'creationTimestamp' : Time,
  'description' : string,
  'visible' : boolean,
  'buttonLabel' : string,
}
export interface MeetingSlot {
  'id' : string,
  'startTime' : Time,
  'description' : string,
  'durationMinutes' : bigint,
  'isBooked' : boolean,
}
export interface Mp3Track {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'order' : bigint,
  'file' : ExternalBlob,
  'playlistId' : string,
  'playCount' : bigint,
  'visible' : boolean,
  'artist' : string,
}
export interface Playlist {
  'id' : string,
  'order' : bigint,
  'name' : string,
  'visible' : boolean,
}
export type ProductType = { 'clothing' : null } |
  { 'other' : string } |
  { 'eBook' : null };
export type SectionType = { 'meetings' : null } |
  { 'custom' : string } |
  { 'blog' : null } |
  { 'links' : null } |
  { 'livestream' : null } |
  { 'mp3Player' : null } |
  { 'storeItems' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SiteContent {
  'businessTitle' : string,
  'blogDescription' : string,
  'meetingDescription' : string,
  'linksTitle' : string,
  'livestreamTitle' : string,
  'storeItemsDescription' : string,
  'meetingTitle' : string,
  'livestreamDescription' : string,
  'mp3PlayerTitle' : string,
  'showLivestreamSection' : boolean,
  'blogTitle' : string,
  'linksDescription' : string,
  'showNewSection' : boolean,
  'storeItemsTitle' : string,
  'showLinksSection' : boolean,
  'showMp3PlayerSection' : boolean,
  'footerContent' : string,
  'mp3PlayerDescription' : string,
}
export interface StoreItem {
  'id' : string,
  'title' : string,
  'description' : string,
  'productType' : ProductType,
  'available' : boolean,
  'coverImage' : ExternalBlob,
  'price' : bigint,
  'previewImages' : Array<ExternalBlob>,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogFile' : ActorMethod<[string, ExternalBlob], string>,
  'addBlogImage' : ActorMethod<
    [string, ExternalBlob, bigint, string, string],
    string
  >,
  'addHomepageSection' : ActorMethod<[HomepageSection], undefined>,
  'addLink' : ActorMethod<[string, string, bigint], string>,
  'addLivestream' : ActorMethod<[string, Time, string, string, string], string>,
  'addMeetingSlot' : ActorMethod<[Time, bigint, string], string>,
  'addStoreItem' : ActorMethod<
    [string, string, bigint, ExternalBlob, ProductType, Array<ExternalBlob>],
    string
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[string, string], string>,
  'cancelAppointment' : ActorMethod<[string], undefined>,
  'createBlogPost' : ActorMethod<[string, string, string], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPlaylist' : ActorMethod<[string], string>,
  'deleteBlogFile' : ActorMethod<[string, string], undefined>,
  'deleteBlogImage' : ActorMethod<[string, string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteHomepageSection' : ActorMethod<[string], undefined>,
  'deleteLink' : ActorMethod<[string], undefined>,
  'deleteLivestream' : ActorMethod<[string], undefined>,
  'deleteMp3Track' : ActorMethod<[string], undefined>,
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllLinks' : ActorMethod<[], Array<LinkItem>>,
  'getAllLivestreams' : ActorMethod<[], Array<Livestream>>,
  'getAllMeetingSlots' : ActorMethod<[], Array<MeetingSlot>>,
  'getAllMp3Tracks' : ActorMethod<[], Array<Mp3Track>>,
  'getAllPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getAllStoreItems' : ActorMethod<[], Array<StoreItem>>,
  'getAllTrackPlayCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getAnalyticsData' : ActorMethod<[], AnalyticsData>,
  'getAvailableMeetingSlots' : ActorMethod<[], Array<MeetingSlot>>,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHomepageSections' : ActorMethod<[], Array<HomepageSection>>,
  'getLivestream' : ActorMethod<[string], [] | [Livestream]>,
  'getMeetingSlot' : ActorMethod<[string], [] | [MeetingSlot]>,
  'getMp3TracksByPlaylist' : ActorMethod<[string], Array<Mp3Track>>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getPublicPlaylists' : ActorMethod<[], Array<Playlist>>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getStoreItem' : ActorMethod<[string], [] | [StoreItem]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTrackPlayCount' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementPlayCount' : ActorMethod<[string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'reorderHomepageSections' : ActorMethod<[Array<string>], undefined>,
  'reorderLinks' : ActorMethod<[Array<string>], undefined>,
  'reorderMp3Tracks' : ActorMethod<[string, Array<string>], undefined>,
  'resetAllTrackPlayCounts' : ActorMethod<[], undefined>,
  'resetTrackPlayCount' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleMp3TrackVisibility' : ActorMethod<[string, boolean], undefined>,
  'togglePlaylistVisibility' : ActorMethod<[string, boolean], undefined>,
  'toggleSectionVisibility' : ActorMethod<[string, boolean], undefined>,
  'trackElementClick' : ActorMethod<[string], undefined>,
  'trackPageVisit' : ActorMethod<[string], undefined>,
  'trackSectionView' : ActorMethod<[string], undefined>,
  'trackUniqueVisitor' : ActorMethod<
    [string],
    { 'dayKey' : string, 'count' : bigint }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBlogDescription' : ActorMethod<[string], undefined>,
  'updateBlogImage' : ActorMethod<
    [string, string, bigint, string, string],
    undefined
  >,
  'updateBlogPost' : ActorMethod<[string, string, string, string], undefined>,
  'updateBlogTitle' : ActorMethod<[string], undefined>,
  'updateBusinessTitle' : ActorMethod<[string], undefined>,
  'updateExcerpt' : ActorMethod<[string, string], undefined>,
  'updateHomepageSection' : ActorMethod<[string, HomepageSection], undefined>,
  'updateLink' : ActorMethod<
    [string, string, string, boolean, bigint],
    undefined
  >,
  'updateLivestream' : ActorMethod<
    [string, string, Time, string, string, string, boolean],
    undefined
  >,
  'updateMeetingSlot' : ActorMethod<[string, Time, bigint, string], undefined>,
  'updateMp3Track' : ActorMethod<
    [string, string, string, bigint, string, boolean, bigint],
    undefined
  >,
  'updatePlaylist' : ActorMethod<[string, string, bigint, boolean], undefined>,
  'updateSiteContent' : ActorMethod<[SiteContent], undefined>,
  'updateStoreItem' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      ExternalBlob,
      ProductType,
      boolean,
      Array<ExternalBlob>,
    ],
    undefined
  >,
  'uploadMp3Track' : ActorMethod<
    [string, string, bigint, ExternalBlob, string, bigint],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];