/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SectionType = IDL.Variant({
  'meetings' : IDL.Null,
  'custom' : IDL.Text,
  'blog' : IDL.Null,
  'links' : IDL.Null,
  'livestream' : IDL.Null,
  'mp3Player' : IDL.Null,
  'storeItems' : IDL.Null,
});
export const HomepageSection = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'sectionType' : SectionType,
  'description' : IDL.Text,
  'visible' : IDL.Bool,
});
export const Time = IDL.Int;
export const ProductType = IDL.Variant({
  'clothing' : IDL.Null,
  'other' : IDL.Text,
  'eBook' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'timeSlotId' : IDL.Text,
  'bookedBy' : IDL.Principal,
});
export const EmbeddedImage = IDL.Record({
  'id' : IDL.Text,
  'url' : ExternalBlob,
  'size' : IDL.Text,
  'position' : IDL.Nat,
  'altText' : IDL.Text,
});
export const EditRecord = IDL.Record({
  'previousTitle' : IDL.Text,
  'editor' : IDL.Principal,
  'previousExcerpt' : IDL.Text,
  'timestamp' : Time,
  'previousContent' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'embeddedImages' : IDL.Vec(EmbeddedImage),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'associatedFiles' : IDL.Vec(ExternalBlob),
  'editHistory' : IDL.Vec(EditRecord),
  'publicationDate' : Time,
  'excerpt' : IDL.Text,
});
export const LinkItem = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'textLabel' : IDL.Text,
  'order' : IDL.Nat,
  'visible' : IDL.Bool,
});
export const Livestream = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'title' : IDL.Text,
  'externalLink' : IDL.Text,
  'creationTimestamp' : Time,
  'description' : IDL.Text,
  'visible' : IDL.Bool,
  'buttonLabel' : IDL.Text,
});
export const MeetingSlot = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'isBooked' : IDL.Bool,
});
export const Mp3Track = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'order' : IDL.Int,
  'file' : ExternalBlob,
  'playlistId' : IDL.Text,
  'playCount' : IDL.Nat,
  'visible' : IDL.Bool,
  'artist' : IDL.Text,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'visible' : IDL.Bool,
});
export const StoreItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'productType' : ProductType,
  'available' : IDL.Bool,
  'coverImage' : ExternalBlob,
  'price' : IDL.Nat,
  'previewImages' : IDL.Vec(ExternalBlob),
});
export const AnalyticsData = IDL.Record({
  'sectionViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'pageVisits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'dailyVisitors' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'elementClicks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const SiteContent = IDL.Record({
  'businessTitle' : IDL.Text,
  'blogDescription' : IDL.Text,
  'meetingDescription' : IDL.Text,
  'linksTitle' : IDL.Text,
  'livestreamTitle' : IDL.Text,
  'storeItemsDescription' : IDL.Text,
  'meetingTitle' : IDL.Text,
  'livestreamDescription' : IDL.Text,
  'mp3PlayerTitle' : IDL.Text,
  'showLivestreamSection' : IDL.Bool,
  'blogTitle' : IDL.Text,
  'linksDescription' : IDL.Text,
  'showNewSection' : IDL.Bool,
  'storeItemsTitle' : IDL.Text,
  'showLinksSection' : IDL.Bool,
  'showMp3PlayerSection' : IDL.Bool,
  'footerContent' : IDL.Text,
  'mp3PlayerDescription' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
  'addBlogImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addHomepageSection' : IDL.Func([HomepageSection], [], []),
  'addLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'addLivestream' : IDL.Func(
      [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addMeetingSlot' : IDL.Func([Time, IDL.Nat, IDL.Text], [IDL.Text], []),
  'addStoreItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ExternalBlob,
        ProductType,
        IDL.Vec(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'cancelAppointment' : IDL.Func([IDL.Text], [], []),
  'createBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPlaylist' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deleteBlogFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteBlogImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteHomepageSection' : IDL.Func([IDL.Text], [], []),
  'deleteLink' : IDL.Func([IDL.Text], [], []),
  'deleteLivestream' : IDL.Func([IDL.Text], [], []),
  'deleteMp3Track' : IDL.Func([IDL.Text], [], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllLinks' : IDL.Func([], [IDL.Vec(LinkItem)], ['query']),
  'getAllLivestreams' : IDL.Func([], [IDL.Vec(Livestream)], ['query']),
  'getAllMeetingSlots' : IDL.Func([], [IDL.Vec(MeetingSlot)], ['query']),
  'getAllMp3Tracks' : IDL.Func([], [IDL.Vec(Mp3Track)], ['query']),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getAllStoreItems' : IDL.Func([], [IDL.Vec(StoreItem)], ['query']),
  'getAllTrackPlayCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
  'getAvailableMeetingSlots' : IDL.Func([], [IDL.Vec(MeetingSlot)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomepageSections' : IDL.Func([], [IDL.Vec(HomepageSection)], ['query']),
  'getLivestream' : IDL.Func([IDL.Text], [IDL.Opt(Livestream)], ['query']),
  'getMeetingSlot' : IDL.Func([IDL.Text], [IDL.Opt(MeetingSlot)], ['query']),
  'getMp3TracksByPlaylist' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Mp3Track)],
      ['query'],
    ),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getStoreItem' : IDL.Func([IDL.Text], [IDL.Opt(StoreItem)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTrackPlayCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementPlayCount' : IDL.Func([IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderHomepageSections' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'reorderLinks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'reorderMp3Tracks' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'resetAllTrackPlayCounts' : IDL.Func([], [], []),
  'resetTrackPlayCount' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleMp3TrackVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'togglePlaylistVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'toggleSectionVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'trackElementClick' : IDL.Func([IDL.Text], [], []),
  'trackPageVisit' : IDL.Func([IDL.Text], [], []),
  'trackSectionView' : IDL.Func([IDL.Text], [], []),
  'trackUniqueVisitor' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'dayKey' : IDL.Text, 'count' : IDL.Nat })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBlogDescription' : IDL.Func([IDL.Text], [], []),
  'updateBlogImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateBlogTitle' : IDL.Func([IDL.Text], [], []),
  'updateBusinessTitle' : IDL.Func([IDL.Text], [], []),
  'updateExcerpt' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateHomepageSection' : IDL.Func([IDL.Text, HomepageSection], [], []),
  'updateLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
      [],
      [],
    ),
  'updateLivestream' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateMeetingSlot' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Text], [], []),
  'updateMp3Track' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Int],
      [],
      [],
    ),
  'updatePlaylist' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'updateSiteContent' : IDL.Func([SiteContent], [], []),
  'updateStoreItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ExternalBlob,
        ProductType,
        IDL.Bool,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
  'uploadMp3Track' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Text, IDL.Int],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SectionType = IDL.Variant({
    'meetings' : IDL.Null,
    'custom' : IDL.Text,
    'blog' : IDL.Null,
    'links' : IDL.Null,
    'livestream' : IDL.Null,
    'mp3Player' : IDL.Null,
    'storeItems' : IDL.Null,
  });
  const HomepageSection = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'sectionType' : SectionType,
    'description' : IDL.Text,
    'visible' : IDL.Bool,
  });
  const Time = IDL.Int;
  const ProductType = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Text,
    'eBook' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'timeSlotId' : IDL.Text,
    'bookedBy' : IDL.Principal,
  });
  const EmbeddedImage = IDL.Record({
    'id' : IDL.Text,
    'url' : ExternalBlob,
    'size' : IDL.Text,
    'position' : IDL.Nat,
    'altText' : IDL.Text,
  });
  const EditRecord = IDL.Record({
    'previousTitle' : IDL.Text,
    'editor' : IDL.Principal,
    'previousExcerpt' : IDL.Text,
    'timestamp' : Time,
    'previousContent' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'embeddedImages' : IDL.Vec(EmbeddedImage),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'associatedFiles' : IDL.Vec(ExternalBlob),
    'editHistory' : IDL.Vec(EditRecord),
    'publicationDate' : Time,
    'excerpt' : IDL.Text,
  });
  const LinkItem = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'textLabel' : IDL.Text,
    'order' : IDL.Nat,
    'visible' : IDL.Bool,
  });
  const Livestream = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'title' : IDL.Text,
    'externalLink' : IDL.Text,
    'creationTimestamp' : Time,
    'description' : IDL.Text,
    'visible' : IDL.Bool,
    'buttonLabel' : IDL.Text,
  });
  const MeetingSlot = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'isBooked' : IDL.Bool,
  });
  const Mp3Track = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'order' : IDL.Int,
    'file' : ExternalBlob,
    'playlistId' : IDL.Text,
    'playCount' : IDL.Nat,
    'visible' : IDL.Bool,
    'artist' : IDL.Text,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'visible' : IDL.Bool,
  });
  const StoreItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'productType' : ProductType,
    'available' : IDL.Bool,
    'coverImage' : ExternalBlob,
    'price' : IDL.Nat,
    'previewImages' : IDL.Vec(ExternalBlob),
  });
  const AnalyticsData = IDL.Record({
    'sectionViews' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'pageVisits' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'dailyVisitors' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'elementClicks' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const SiteContent = IDL.Record({
    'businessTitle' : IDL.Text,
    'blogDescription' : IDL.Text,
    'meetingDescription' : IDL.Text,
    'linksTitle' : IDL.Text,
    'livestreamTitle' : IDL.Text,
    'storeItemsDescription' : IDL.Text,
    'meetingTitle' : IDL.Text,
    'livestreamDescription' : IDL.Text,
    'mp3PlayerTitle' : IDL.Text,
    'showLivestreamSection' : IDL.Bool,
    'blogTitle' : IDL.Text,
    'linksDescription' : IDL.Text,
    'showNewSection' : IDL.Bool,
    'storeItemsTitle' : IDL.Text,
    'showLinksSection' : IDL.Bool,
    'showMp3PlayerSection' : IDL.Bool,
    'footerContent' : IDL.Text,
    'mp3PlayerDescription' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Text], []),
    'addBlogImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addHomepageSection' : IDL.Func([HomepageSection], [], []),
    'addLink' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'addLivestream' : IDL.Func(
        [IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addMeetingSlot' : IDL.Func([Time, IDL.Nat, IDL.Text], [IDL.Text], []),
    'addStoreItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          ProductType,
          IDL.Vec(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'cancelAppointment' : IDL.Func([IDL.Text], [], []),
    'createBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPlaylist' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deleteBlogFile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteBlogImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteHomepageSection' : IDL.Func([IDL.Text], [], []),
    'deleteLink' : IDL.Func([IDL.Text], [], []),
    'deleteLivestream' : IDL.Func([IDL.Text], [], []),
    'deleteMp3Track' : IDL.Func([IDL.Text], [], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllLinks' : IDL.Func([], [IDL.Vec(LinkItem)], ['query']),
    'getAllLivestreams' : IDL.Func([], [IDL.Vec(Livestream)], ['query']),
    'getAllMeetingSlots' : IDL.Func([], [IDL.Vec(MeetingSlot)], ['query']),
    'getAllMp3Tracks' : IDL.Func([], [IDL.Vec(Mp3Track)], ['query']),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getAllStoreItems' : IDL.Func([], [IDL.Vec(StoreItem)], ['query']),
    'getAllTrackPlayCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
    'getAvailableMeetingSlots' : IDL.Func(
        [],
        [IDL.Vec(MeetingSlot)],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomepageSections' : IDL.Func([], [IDL.Vec(HomepageSection)], ['query']),
    'getLivestream' : IDL.Func([IDL.Text], [IDL.Opt(Livestream)], ['query']),
    'getMeetingSlot' : IDL.Func([IDL.Text], [IDL.Opt(MeetingSlot)], ['query']),
    'getMp3TracksByPlaylist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Mp3Track)],
        ['query'],
      ),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getPublicPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getStoreItem' : IDL.Func([IDL.Text], [IDL.Opt(StoreItem)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTrackPlayCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementPlayCount' : IDL.Func([IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderHomepageSections' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'reorderLinks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'reorderMp3Tracks' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'resetAllTrackPlayCounts' : IDL.Func([], [], []),
    'resetTrackPlayCount' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleMp3TrackVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'togglePlaylistVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'toggleSectionVisibility' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'trackElementClick' : IDL.Func([IDL.Text], [], []),
    'trackPageVisit' : IDL.Func([IDL.Text], [], []),
    'trackSectionView' : IDL.Func([IDL.Text], [], []),
    'trackUniqueVisitor' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'dayKey' : IDL.Text, 'count' : IDL.Nat })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBlogDescription' : IDL.Func([IDL.Text], [], []),
    'updateBlogImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBlogTitle' : IDL.Func([IDL.Text], [], []),
    'updateBusinessTitle' : IDL.Func([IDL.Text], [], []),
    'updateExcerpt' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateHomepageSection' : IDL.Func([IDL.Text, HomepageSection], [], []),
    'updateLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Nat],
        [],
        [],
      ),
    'updateLivestream' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateMeetingSlot' : IDL.Func([IDL.Text, Time, IDL.Nat, IDL.Text], [], []),
    'updateMp3Track' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Int],
        [],
        [],
      ),
    'updatePlaylist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateSiteContent' : IDL.Func([SiteContent], [], []),
    'updateStoreItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          ProductType,
          IDL.Bool,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
    'uploadMp3Track' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Text, IDL.Int],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };