/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AnalyticsData {
    sectionViews: Array<[string, bigint]>;
    pageVisits: Array<[string, bigint]>;
    dailyVisitors: Array<[string, bigint]>;
    elementClicks: Array<[string, bigint]>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Mp3Track {
    id: string;
    title: string;
    duration: bigint;
    order: bigint;
    file: ExternalBlob;
    playlistId: string;
    playCount: bigint;
    visible: boolean;
    artist: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type SectionType = {
    __kind__: "meetings";
    meetings: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blog";
    blog: null;
} | {
    __kind__: "links";
    links: null;
} | {
    __kind__: "livestream";
    livestream: null;
} | {
    __kind__: "mp3Player";
    mp3Player: null;
} | {
    __kind__: "storeItems";
    storeItems: null;
};
export interface EmbeddedImage {
    id: string;
    url: ExternalBlob;
    size: string;
    position: bigint;
    altText: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface HomepageSection {
    id: string;
    title: string;
    order: bigint;
    sectionType: SectionType;
    description: string;
    visible: boolean;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SiteContent {
    businessTitle: string;
    blogDescription: string;
    meetingDescription: string;
    linksTitle: string;
    livestreamTitle: string;
    storeItemsDescription: string;
    meetingTitle: string;
    livestreamDescription: string;
    mp3PlayerTitle: string;
    showLivestreamSection: boolean;
    blogTitle: string;
    linksDescription: string;
    showNewSection: boolean;
    storeItemsTitle: string;
    showLinksSection: boolean;
    showMp3PlayerSection: boolean;
    footerContent: string;
    mp3PlayerDescription: string;
}
export interface EditRecord {
    previousTitle: string;
    editor: Principal;
    previousExcerpt: string;
    timestamp: Time;
    previousContent: string;
}
export interface BlogPost {
    id: string;
    embeddedImages: Array<EmbeddedImage>;
    title: string;
    content: string;
    associatedFiles: Array<ExternalBlob>;
    editHistory: Array<EditRecord>;
    publicationDate: Time;
    excerpt: string;
}
export interface MeetingSlot {
    id: string;
    startTime: Time;
    description: string;
    durationMinutes: bigint;
    isBooked: boolean;
}
export type ProductType = {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "eBook";
    eBook: null;
};
export interface Playlist {
    id: string;
    order: bigint;
    name: string;
    visible: boolean;
}
export interface Livestream {
    id: string;
    startTime: Time;
    title: string;
    externalLink: string;
    creationTimestamp: Time;
    description: string;
    visible: boolean;
    buttonLabel: string;
}
export interface LinkItem {
    id: string;
    url: string;
    textLabel: string;
    order: bigint;
    visible: boolean;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface StoreItem {
    id: string;
    title: string;
    description: string;
    productType: ProductType;
    available: boolean;
    coverImage: ExternalBlob;
    price: bigint;
    previewImages: Array<ExternalBlob>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Appointment {
    id: string;
    customerName: string;
    timeSlotId: string;
    bookedBy: Principal;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBlogFile(blogId: string, file: ExternalBlob): Promise<string>;
    addBlogImage(blogId: string, imageUrl: ExternalBlob, position: bigint, altText: string, size: string): Promise<string>;
    addHomepageSection(section: HomepageSection): Promise<void>;
    addLink(textLabel: string, url: string, order: bigint): Promise<string>;
    addLivestream(title: string, startTime: Time, externalLink: string, buttonLabel: string, description: string): Promise<string>;
    addMeetingSlot(startTime: Time, durationMinutes: bigint, description: string): Promise<string>;
    addStoreItem(title: string, description: string, price: bigint, coverImage: ExternalBlob, productType: ProductType, previewImages: Array<ExternalBlob>): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(customerName: string, timeSlotId: string): Promise<string>;
    cancelAppointment(appointmentId: string): Promise<void>;
    clearAnalyticsData(): Promise<void>;
    createBlogPost(title: string, content: string, excerpt: string): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPlaylist(name: string): Promise<string>;
    deleteBlogFile(blogId: string, _filePath: string): Promise<void>;
    deleteBlogImage(blogId: string, imageId: string): Promise<void>;
    deleteBlogPost(id: string): Promise<void>;
    deleteHomepageSection(id: string): Promise<void>;
    deleteLink(id: string): Promise<void>;
    deleteLivestream(id: string): Promise<void>;
    deleteMp3Track(id: string): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllLinks(): Promise<Array<LinkItem>>;
    getAllLivestreams(): Promise<Array<Livestream>>;
    getAllMeetingSlots(): Promise<Array<MeetingSlot>>;
    getAllMp3Tracks(): Promise<Array<Mp3Track>>;
    getAllPlaylists(): Promise<Array<Playlist>>;
    getAllStoreItems(): Promise<Array<StoreItem>>;
    getAllTrackPlayCounts(): Promise<Array<[string, bigint]>>;
    getAnalyticsData(): Promise<AnalyticsData>;
    getAvailableMeetingSlots(): Promise<Array<MeetingSlot>>;
    getBlogPost(id: string): Promise<BlogPost | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHomepageSections(): Promise<Array<HomepageSection>>;
    getLivestream(id: string): Promise<Livestream | null>;
    getMeetingSlot(id: string): Promise<MeetingSlot | null>;
    getMp3TracksByPlaylist(playlistId: string): Promise<Array<Mp3Track>>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getPublicPlaylists(): Promise<Array<Playlist>>;
    getSiteContent(): Promise<SiteContent>;
    getStoreItem(id: string): Promise<StoreItem | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTrackPlayCount(trackId: string): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementPlayCount(trackId: string): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    reorderHomepageSections(newOrder: Array<string>): Promise<void>;
    reorderLinks(newOrder: Array<string>): Promise<void>;
    reorderMp3Tracks(playlistId: string, newOrder: Array<string>): Promise<void>;
    resetAllTrackPlayCounts(): Promise<void>;
    resetTrackPlayCount(trackId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleMp3TrackVisibility(id: string, visible: boolean): Promise<void>;
    togglePlaylistVisibility(id: string, visible: boolean): Promise<void>;
    toggleSectionVisibility(id: string, visible: boolean): Promise<void>;
    trackElementClick(element: string): Promise<void>;
    trackPageVisit(page: string): Promise<void>;
    trackSectionView(sectionId: string): Promise<void>;
    trackUniqueVisitor(_sessionId: string): Promise<{
        dayKey: string;
        count: bigint;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBlogDescription(description: string): Promise<void>;
    updateBlogImage(blogId: string, imageId: string, position: bigint, size: string, altText: string): Promise<void>;
    updateBlogPost(id: string, newTitle: string, newContent: string, newExcerpt: string): Promise<void>;
    updateBlogTitle(title: string): Promise<void>;
    updateBusinessTitle(newTitle: string): Promise<void>;
    updateExcerpt(id: string, newExcerpt: string): Promise<void>;
    updateHomepageSection(id: string, updatedSection: HomepageSection): Promise<void>;
    updateLink(id: string, textLabel: string, url: string, visible: boolean, order: bigint): Promise<void>;
    updateLivestream(id: string, title: string, startTime: Time, externalLink: string, buttonLabel: string, description: string, visible: boolean): Promise<void>;
    updateMeetingSlot(id: string, startTime: Time, durationMinutes: bigint, description: string): Promise<void>;
    updateMp3Track(id: string, title: string, artist: string, duration: bigint, playlistId: string, visible: boolean, order: bigint): Promise<void>;
    updatePlaylist(id: string, name: string, order: bigint, visible: boolean): Promise<void>;
    updateSiteContent(newContent: SiteContent): Promise<void>;
    updateStoreItem(id: string, title: string, description: string, price: bigint, coverImage: ExternalBlob, productType: ProductType, available: boolean, previewImages: Array<ExternalBlob>): Promise<void>;
    uploadMp3Track(title: string, artist: string, duration: bigint, file: ExternalBlob, playlistId: string, order: bigint): Promise<string>;
}
import type { BlogPost as _BlogPost, EditRecord as _EditRecord, EmbeddedImage as _EmbeddedImage, ExternalBlob as _ExternalBlob, HomepageSection as _HomepageSection, Livestream as _Livestream, MeetingSlot as _MeetingSlot, Mp3Track as _Mp3Track, ProductType as _ProductType, SectionType as _SectionType, StoreItem as _StoreItem, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBlogFile(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogFile(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogFile(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addBlogImage(arg0: string, arg1: ExternalBlob, arg2: bigint, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogImage(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async addHomepageSection(arg0: HomepageSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHomepageSection(to_candid_HomepageSection_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHomepageSection(to_candid_HomepageSection_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addLink(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLink(arg0, arg1, arg2);
            return result;
        }
    }
    async addLivestream(arg0: string, arg1: Time, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLivestream(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLivestream(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMeetingSlot(arg0: Time, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeetingSlot(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeetingSlot(arg0, arg1, arg2);
            return result;
        }
    }
    async addStoreItem(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob, arg4: ProductType, arg5: Array<ExternalBlob>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStoreItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), to_candid_ProductType_n13(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStoreItem(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), to_candid_ProductType_n13(this._uploadFile, this._downloadFile, arg4), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1);
            return result;
        }
    }
    async cancelAppointment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async clearAnalyticsData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAnalyticsData();
            return result;
        }
    }
    async createBlogPost(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, arg1, arg2);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPlaylist(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0);
            return result;
        }
    }
    async deleteBlogFile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogFile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogFile(arg0, arg1);
            return result;
        }
    }
    async deleteBlogImage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogImage(arg0, arg1);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteHomepageSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHomepageSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHomepageSection(arg0);
            return result;
        }
    }
    async deleteLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLink(arg0);
            return result;
        }
    }
    async deleteLivestream(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLivestream(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLivestream(arg0);
            return result;
        }
    }
    async deleteMp3Track(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMp3Track(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMp3Track(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLinks(): Promise<Array<LinkItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLinks();
            return result;
        }
    }
    async getAllLivestreams(): Promise<Array<Livestream>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLivestreams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLivestreams();
            return result;
        }
    }
    async getAllMeetingSlots(): Promise<Array<MeetingSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMeetingSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMeetingSlots();
            return result;
        }
    }
    async getAllMp3Tracks(): Promise<Array<Mp3Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMp3Tracks();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMp3Tracks();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlaylists();
            return result;
        }
    }
    async getAllStoreItems(): Promise<Array<StoreItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStoreItems();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStoreItems();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrackPlayCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrackPlayCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrackPlayCounts();
            return result;
        }
    }
    async getAnalyticsData(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return result;
        }
    }
    async getAvailableMeetingSlots(): Promise<Array<MeetingSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableMeetingSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableMeetingSlots();
            return result;
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomepageSections(): Promise<Array<HomepageSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageSections();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageSections();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLivestream(arg0: string): Promise<Livestream | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivestream(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivestream(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeetingSlot(arg0: string): Promise<MeetingSlot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetingSlot(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetingSlot(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMp3TracksByPlaylist(arg0: string): Promise<Array<Mp3Track>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMp3TracksByPlaylist(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMp3TracksByPlaylist(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return result;
        }
    }
    async getPublicPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPlaylists();
            return result;
        }
    }
    async getSiteContent(): Promise<SiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteContent();
            return result;
        }
    }
    async getStoreItem(arg0: string): Promise<StoreItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreItem(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreItem(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrackPlayCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrackPlayCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrackPlayCount(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementPlayCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementPlayCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementPlayCount(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async reorderHomepageSections(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderHomepageSections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderHomepageSections(arg0);
            return result;
        }
    }
    async reorderLinks(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderLinks(arg0);
            return result;
        }
    }
    async reorderMp3Tracks(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderMp3Tracks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderMp3Tracks(arg0, arg1);
            return result;
        }
    }
    async resetAllTrackPlayCounts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllTrackPlayCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllTrackPlayCounts();
            return result;
        }
    }
    async resetTrackPlayCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTrackPlayCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTrackPlayCount(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleMp3TrackVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMp3TrackVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMp3TrackVisibility(arg0, arg1);
            return result;
        }
    }
    async togglePlaylistVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePlaylistVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePlaylistVisibility(arg0, arg1);
            return result;
        }
    }
    async toggleSectionVisibility(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSectionVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSectionVisibility(arg0, arg1);
            return result;
        }
    }
    async trackElementClick(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackElementClick(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackElementClick(arg0);
            return result;
        }
    }
    async trackPageVisit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackPageVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackPageVisit(arg0);
            return result;
        }
    }
    async trackSectionView(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackSectionView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackSectionView(arg0);
            return result;
        }
    }
    async trackUniqueVisitor(arg0: string): Promise<{
        dayKey: string;
        count: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.trackUniqueVisitor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackUniqueVisitor(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBlogDescription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogDescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogDescription(arg0);
            return result;
        }
    }
    async updateBlogImage(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogImage(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogImage(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBlogTitle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogTitle(arg0);
            return result;
        }
    }
    async updateBusinessTitle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessTitle(arg0);
            return result;
        }
    }
    async updateExcerpt(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExcerpt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExcerpt(arg0, arg1);
            return result;
        }
    }
    async updateHomepageSection(arg0: string, arg1: HomepageSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageSection(arg0, to_candid_HomepageSection_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageSection(arg0, to_candid_HomepageSection_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLink(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLink(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLink(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateLivestream(arg0: string, arg1: string, arg2: Time, arg3: string, arg4: string, arg5: string, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLivestream(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLivestream(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateMeetingSlot(arg0: string, arg1: Time, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeetingSlot(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeetingSlot(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateMp3Track(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: boolean, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMp3Track(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMp3Track(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updatePlaylist(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaylist(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaylist(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSiteContent(arg0: SiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSiteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSiteContent(arg0);
            return result;
        }
    }
    async updateStoreItem(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: ExternalBlob, arg5: ProductType, arg6: boolean, arg7: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStoreItem(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), to_candid_ProductType_n13(this._uploadFile, this._downloadFile, arg5), arg6, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStoreItem(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), to_candid_ProductType_n13(this._uploadFile, this._downloadFile, arg5), arg6, await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async uploadMp3Track(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob, arg4: string, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMp3Track(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMp3Track(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
async function from_candid_BlogPost_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_EmbeddedImage_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmbeddedImage): Promise<EmbeddedImage> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HomepageSection_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageSection): HomepageSection {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_Mp3Track_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mp3Track): Promise<Mp3Track> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SectionType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SectionType): SectionType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_StoreItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreItem): Promise<StoreItem> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Livestream]): Livestream | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MeetingSlot]): MeetingSlot | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoreItem]): Promise<StoreItem | null> {
    return value.length === 0 ? null : await from_candid_StoreItem_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    embeddedImages: Array<_EmbeddedImage>;
    title: string;
    content: string;
    associatedFiles: Array<_ExternalBlob>;
    editHistory: Array<_EditRecord>;
    publicationDate: _Time;
    excerpt: string;
}): Promise<{
    id: string;
    embeddedImages: Array<EmbeddedImage>;
    title: string;
    content: string;
    associatedFiles: Array<ExternalBlob>;
    editHistory: Array<EditRecord>;
    publicationDate: Time;
    excerpt: string;
}> {
    return {
        id: value.id,
        embeddedImages: await from_candid_vec_n21(_uploadFile, _downloadFile, value.embeddedImages),
        title: value.title,
        content: value.content,
        associatedFiles: await from_candid_vec_n25(_uploadFile, _downloadFile, value.associatedFiles),
        editHistory: value.editHistory,
        publicationDate: value.publicationDate,
        excerpt: value.excerpt
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: _ExternalBlob;
    size: string;
    position: bigint;
    altText: string;
}): Promise<{
    id: string;
    url: ExternalBlob;
    size: string;
    position: bigint;
    altText: string;
}> {
    return {
        id: value.id,
        url: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.url),
        size: value.size,
        position: value.position,
        altText: value.altText
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    order: bigint;
    file: _ExternalBlob;
    playlistId: string;
    playCount: bigint;
    visible: boolean;
    artist: string;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    order: bigint;
    file: ExternalBlob;
    playlistId: string;
    playCount: bigint;
    visible: boolean;
    artist: string;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        order: value.order,
        file: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.file),
        playlistId: value.playlistId,
        playCount: value.playCount,
        visible: value.visible,
        artist: value.artist
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    productType: _ProductType;
    available: boolean;
    coverImage: _ExternalBlob;
    price: bigint;
    previewImages: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    title: string;
    description: string;
    productType: ProductType;
    available: boolean;
    coverImage: ExternalBlob;
    price: bigint;
    previewImages: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        productType: from_candid_ProductType_n32(_uploadFile, _downloadFile, value.productType),
        available: value.available,
        coverImage: await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value.coverImage),
        price: value.price,
        previewImages: await from_candid_vec_n25(_uploadFile, _downloadFile, value.previewImages)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    order: bigint;
    sectionType: _SectionType;
    description: string;
    visible: boolean;
}): {
    id: string;
    title: string;
    order: bigint;
    sectionType: SectionType;
    description: string;
    visible: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        sectionType: from_candid_SectionType_n41(_uploadFile, _downloadFile, value.sectionType),
        description: value.description,
        visible: value.visible
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clothing: null;
} | {
    other: string;
} | {
    eBook: null;
}): {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "eBook";
    eBook: null;
} {
    return "clothing" in value ? {
        __kind__: "clothing",
        clothing: value.clothing
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "eBook" in value ? {
        __kind__: "eBook",
        eBook: value.eBook
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meetings: null;
} | {
    custom: string;
} | {
    blog: null;
} | {
    links: null;
} | {
    livestream: null;
} | {
    mp3Player: null;
} | {
    storeItems: null;
}): {
    __kind__: "meetings";
    meetings: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blog";
    blog: null;
} | {
    __kind__: "links";
    links: null;
} | {
    __kind__: "livestream";
    livestream: null;
} | {
    __kind__: "mp3Player";
    mp3Player: null;
} | {
    __kind__: "storeItems";
    storeItems: null;
} {
    return "meetings" in value ? {
        __kind__: "meetings",
        meetings: value.meetings
    } : "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "blog" in value ? {
        __kind__: "blog",
        blog: value.blog
    } : "links" in value ? {
        __kind__: "links",
        links: value.links
    } : "livestream" in value ? {
        __kind__: "livestream",
        livestream: value.livestream
    } : "mp3Player" in value ? {
        __kind__: "mp3Player",
        mp3Player: value.mp3Player
    } : "storeItems" in value ? {
        __kind__: "storeItems",
        storeItems: value.storeItems
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n48(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n19(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmbeddedImage>): Promise<Array<EmbeddedImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EmbeddedImage_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Mp3Track>): Promise<Array<Mp3Track>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Mp3Track_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoreItem>): Promise<Array<StoreItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoreItem_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HomepageSection>): Array<HomepageSection> {
    return value.map((x)=>from_candid_HomepageSection_n39(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HomepageSection_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomepageSection): _HomepageSection {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SectionType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SectionType): _SectionType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    order: bigint;
    sectionType: SectionType;
    description: string;
    visible: boolean;
}): {
    id: string;
    title: string;
    order: bigint;
    sectionType: _SectionType;
    description: string;
    visible: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        order: value.order,
        sectionType: to_candid_SectionType_n11(_uploadFile, _downloadFile, value.sectionType),
        description: value.description,
        visible: value.visible
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "meetings";
    meetings: null;
} | {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "blog";
    blog: null;
} | {
    __kind__: "links";
    links: null;
} | {
    __kind__: "livestream";
    livestream: null;
} | {
    __kind__: "mp3Player";
    mp3Player: null;
} | {
    __kind__: "storeItems";
    storeItems: null;
}): {
    meetings: null;
} | {
    custom: string;
} | {
    blog: null;
} | {
    links: null;
} | {
    livestream: null;
} | {
    mp3Player: null;
} | {
    storeItems: null;
} {
    return value.__kind__ === "meetings" ? {
        meetings: value.meetings
    } : value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "blog" ? {
        blog: value.blog
    } : value.__kind__ === "links" ? {
        links: value.links
    } : value.__kind__ === "livestream" ? {
        livestream: value.livestream
    } : value.__kind__ === "mp3Player" ? {
        mp3Player: value.mp3Player
    } : value.__kind__ === "storeItems" ? {
        storeItems: value.storeItems
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "clothing";
    clothing: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "eBook";
    eBook: null;
}): {
    clothing: null;
} | {
    other: string;
} | {
    eBook: null;
} {
    return value.__kind__ === "clothing" ? {
        clothing: value.clothing
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "eBook" ? {
        eBook: value.eBook
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
